Games/Models/Feedback.cs
using System.ComponentModel.DataAnnotations;

namespace Games.Models
{
    public class Feedback
    {
        [Display(Name = "Имя")]
        [StringLength(50, MinimumLength = 2, ErrorMessage = "Некорректная длина имени!")]
        [Required(ErrorMessage = "Поле необходимо заполнить!")]
        public string Name { get; set; }

        [Display(Name = "Фамилия")]
        [StringLength(50, MinimumLength = 2, ErrorMessage = "Некорректная длина фамилии!")]
        [Required(ErrorMessage = "Поле необходимо заполнить!")]
        public string Surname { get; set;}

        [Display(Name = "Возраст")]
        [Required(ErrorMessage = "Поле необходимо заполнить!")]
        public int Age { get; set;}

        [Display(Name = "Электронная почта")]
        [StringLength(70, MinimumLength = 2, ErrorMessage = "Некорректная длина адреса электронной почты!")]
        [Required(ErrorMessage = "Поле необходимо заполнить!")]
        public string Email { get; set;}

        [Display(Name = "Сообщение")]
        [StringLength(1000, MinimumLength = 10, ErrorMessage = "Некорректная длина Сообщения!")]
        [Required(ErrorMessage = "Поле необходимо заполнить!")]
        public string Message { get; set;}
    }
}

Games/Controllers/FeedbackController.cs
using Microsoft.AspNetCore.Mvc;
using Games.Models;
using Games.Services;

namespace Games.Controllers
{
    public class FeedbackController : Controller
    {
        private readonly EmailService _emailService;
        private readonly TelegramService _telegramService;

        public FeedbackController(EmailService emailService, TelegramService telegramService)
        {
            _emailService = emailService;
            _telegramService = telegramService;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Check(Feedback feedback)
        {
            if (!ModelState.IsValid)
                return View("Index");

            string message = $"Имя: {feedback.Name} {feedback.Surname}\n" +
                             $"Возраст: {feedback.Age}\n" +
                             $"Email: {feedback.Email}\n" +
                             $"Сообщение: {feedback.Message}";

            await _emailService.SendEmail("Поступил новый отзыв", message, "denis.ladovir@yandex.ru");
            await _telegramService.SendMessageAsync(message);

            return Redirect("/");
        }
    }
}

Games/Views/Feedback/Index.cshtml
@model Feedback
@{
    ViewData["Title"] = "Обратная связь";
}
<form method="post" asp-controller="Feedback" asp-action="Check">
    <label asp-for="Name"></label>
    <input asp-for="Name" />
    <span asp-validation-for="Name"></span>

    <label asp-for="Surname"></label>
    <input asp-for="Surname" />
    <span asp-validation-for="Surname"></span>

    <label asp-for="Age"></label>
    <input asp-for="Age" />
    <span asp-validation-for="Age"></span>

    <label asp-for="Email"></label>
    <input asp-for="Email" />
    <span asp-validation-for="Email"></span>

    <label asp-for="Message"></label>
    <input asp-for="Message" />
    <span asp-validation-for="Message"></span>

    <input type="submit" value="Отправить"
</form>